INSTALL_DIRECTORY = /local/data/public/2021/sct58/Project/cash2-s.BINF2018/local

.c:
	gcc -O3 -Wall -o $@ $< -L$(INSTALL_DIRECTORY)/lib -I$(INSTALL_DIRECTORY)/include -lcash2-s -lc -lpng -lz -lX11 -lm -lgrace_np
