INSTALL_DIRECTORY = /home/sandro/cash2-s.BINF2018/local

.c:
	gcc -O0 -g -Wall -o $@ $< -L$(INSTALL_DIRECTORY)/lib -I$(INSTALL_DIRECTORY)/include -lcash2-s -lc -lpng -lz -lX11 -lm -lgrace_np
#	gcc -O3 -Wall -o $@ $< -L$(INSTALL_DIRECTORY)/lib -I$(INSTALL_DIRECTORY)/include -lcash2-s -lc -lpng -lz -lX11 -lm -lgrace_np
